(cl:defpackage ogretici_paket-msg
  (:use )
  (:export
   "<BATARYA_DURUM>"
   "BATARYA_DURUM"
   "<GOREVDURUMACTION>"
   "GOREVDURUMACTION"
   "<GOREVDURUMACTIONFEEDBACK>"
   "GOREVDURUMACTIONFEEDBACK"
   "<GOREVDURUMACTIONGOAL>"
   "GOREVDURUMACTIONGOAL"
   "<GOREVDURUMACTIONRESULT>"
   "GOREVDURUMACTIONRESULT"
   "<GOREVDURUMFEEDBACK>"
   "GOREVDURUMFEEDBACK"
   "<GOREVDURUMGOAL>"
   "GOREVDURUMGOAL"
   "<GOREVDURUMRESULT>"
   "GOREVDURUMRESULT"
  ))

